(()=>{
 let library;
 const pdfLibrary=()=>library||(library=import('/assets/vendor/pdfjs/pdf.min.js').then(pdf=>{pdf.GlobalWorkerOptions.workerSrc='/assets/vendor/pdfjs/pdf.worker.min.js';return pdf;}).catch(error=>{library=null;throw error;}));
 window.rpMountPdf=async(host,source)=>{
  host._pdfCleanup?.();let disposed=false,documentPdf,loadingTask,renderTask,revision=0,pageNumber=1,zoom=1;
  host.classList.add('rp-pdf-viewer');host.innerHTML='<div class="rp-document-tools"><button type="button" data-prev aria-label="Página anterior">←</button><span data-count role="status">Cargando PDF…</span><button type="button" data-next aria-label="Página siguiente">→</button><button type="button" data-out aria-label="Reducir zoom">−</button><button type="button" data-fit>Ajustar</button><button type="button" data-in aria-label="Ampliar zoom">+</button></div><div class="rp-pdf-scroll" tabindex="0" aria-label="Página del PDF, desplazable"><canvas></canvas></div><p class="rp-pdf-error" role="alert" hidden></p>';
  const canvas=host.querySelector('canvas'),scroll=host.querySelector('.rp-pdf-scroll'),count=host.querySelector('[data-count]');
  const cleanup=()=>{disposed=true;revision++;renderTask?.cancel();observer.disconnect();loadingTask?.destroy();};host._pdfCleanup=cleanup;
  const render=async()=>{if(!documentPdf||disposed)return;const current=++revision;const pending=renderTask;pending?.cancel();try{if(pending)await pending.promise.catch(()=>{});if(current!==revision||disposed)return;const page=await documentPdf.getPage(pageNumber);if(current!==revision||disposed)return;const natural=page.getViewport({scale:1}),scale=Math.max(.1,(scroll.clientWidth-24)/natural.width)*zoom,viewport=page.getViewport({scale}),ratio=Math.min(devicePixelRatio||1,2);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';canvas.width=Math.ceil(viewport.width*ratio);canvas.height=Math.ceil(viewport.height*ratio);renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:[ratio,0,0,ratio,0,0]});await renderTask.promise;if(current!==revision)return;count.textContent=`Página ${pageNumber} de ${documentPdf.numPages}`;canvas.setAttribute('aria-label',count.textContent);host.dataset.pages=documentPdf.numPages;host.querySelector('[data-prev]').disabled=pageNumber===1;host.querySelector('[data-next]').disabled=pageNumber===documentPdf.numPages;}catch(error){if(error.name!=='RenderingCancelledException'&&!disposed){host.querySelector('.rp-pdf-error').hidden=false;host.querySelector('.rp-pdf-error').textContent='No se pudo mostrar esta página. Descarga el PDF para abrirlo.';}}};
  const observer=new ResizeObserver(()=>render());observer.observe(scroll);
  host.querySelector('[data-prev]').onclick=()=>{if(pageNumber>1){pageNumber--;scroll.scrollTo(0,0);render();}};
  host.querySelector('[data-next]').onclick=()=>{if(documentPdf&&pageNumber<documentPdf.numPages){pageNumber++;scroll.scrollTo(0,0);render();}};
  host.querySelector('[data-out]').onclick=()=>{zoom=Math.max(1,zoom-.5);render();};host.querySelector('[data-in]').onclick=()=>{zoom=Math.min(4,zoom+.5);render();};host.querySelector('[data-fit]').onclick=()=>{zoom=1;scroll.scrollTo(0,0);render();};
  try{const pdf=await pdfLibrary();if(disposed)return;const data=source instanceof Blob?new Uint8Array(await source.arrayBuffer()):source;loadingTask=pdf.getDocument({...(typeof data==='string'?{url:data}:{data}),standardFontDataUrl:'/assets/vendor/pdfjs/standard_fonts/',wasmUrl:'/assets/vendor/pdfjs/wasm/',isEvalSupported:false});documentPdf=await loadingTask.promise;if(disposed){loadingTask.destroy();return;}await render();}catch(error){if(!disposed){count.textContent='Vista previa no disponible';host.querySelector('.rp-pdf-error').hidden=false;host.querySelector('.rp-pdf-error').textContent='Descarga el archivo para abrirlo en tu lector PDF.';console.error(error);}}
  return cleanup;
 };
 // Scale the whole paper instead of reflowing its columns on small screens.
 const enhance=paper=>{if(paper.dataset.previewReady)return;paper.dataset.previewReady='true';const parent=paper.parentElement,stage=document.createElement('div'),tools=document.createElement('div');stage.className='rp-paper-stage';tools.className='rp-document-tools';tools.innerHTML='<span>Vista de documento</span><button type="button" data-fit>Ajustar</button><button type="button" data-full>100%</button><button type="button" data-more aria-label="Ampliar documento">+</button>';paper.before(tools,stage);stage.append(paper);let userZoom=0;
 const resize=()=>{if(!paper.isConnected){observer.disconnect();return;}if(!parent.clientWidth)return;const width=paper.offsetWidth,height=paper.offsetHeight,fit=Math.min(1,Math.max(100,parent.clientWidth-40)/width),scale=userZoom||fit;paper.style.transform=`scale(${scale})`;paper.style.transformOrigin='top left';stage.style.width=width*scale+'px';stage.style.height=height*scale+'px';};
 tools.querySelector('[data-fit]').onclick=()=>{userZoom=0;resize();};tools.querySelector('[data-full]').onclick=()=>{userZoom=1;resize();};tools.querySelector('[data-more]').onclick=()=>{userZoom=Math.min(2,(userZoom||Math.min(1,(parent.clientWidth-40)/paper.offsetWidth))+.25);resize();};const observer=new ResizeObserver(resize);observer.observe(parent);observer.observe(paper);resize();
 };
 const scan=()=>document.querySelectorAll('.rent-report-paper,.proposal-preview-paper,.approved-history-paper').forEach(enhance);
 document.addEventListener('DOMContentLoaded',()=>{scan();new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});});
 window.rpPaperCaptureOptions=paper=>({width:paper.offsetWidth,height:paper.scrollHeight,windowWidth:1280,onclone:doc=>{const copy=paper.id?doc.getElementById(paper.id):doc.querySelector('.'+[...paper.classList].find(c=>/paper/.test(c)));if(copy){doc.body.append(copy);copy.style.cssText+=';transform:none!important;position:fixed;left:0;top:0;margin:0;';}}});
})();
