document.addEventListener('DOMContentLoaded',()=>{
  const key='rp-scheduled-alerts',today=new Date();today.setHours(0,0,0,0);
  const seed=[
    {id:'ALT-001',type:'Alerta Preventiva (60 días)',local:'Rico’s',contractId:'CTR-8800',station:'La Marina',city:'Mazatlán',scheduledDate:'2026-08-31',recipients:['Alyn Ximena Reyes Navarrete','Área Legal'],recipientEmails:['alyn@redpetroil.com','legal@redpetroil.com'],priority:'high',title:'Alerta preventiva: Rico’s · La Marina',description:'Iniciar la revisión anticipada del contrato y preparar la documentación de renovación.'},
    {id:'ALT-002',type:'Pago Mensual',local:'Farmacia Moderna',contractId:'CTR-8801',station:'Cerritos',city:'Mazatlán',scheduledDate:'2026-09-01',recipients:['Alyn Ximena Reyes Navarrete'],recipientEmails:['alyn@redpetroil.com'],priority:'medium',title:'Pago mensual: Farmacia Moderna · Cerritos',description:'Confirmar recepción y aplicación del pago mensual.'},
    {id:'ALT-003',type:'Incremento de Renta',local:'Restaurante',contractId:'CTR-8802',station:'Cardones',city:'Mazatlán',scheduledDate:'2026-09-05',recipients:['Alyn Ximena Reyes Navarrete','Área Legal'],recipientEmails:['alyn@redpetroil.com','legal@redpetroil.com'],priority:'high',title:'Incremento de renta: Restaurante · Cardones',description:'Validar el incremento pactado y preparar la notificación contractual.'},
    {id:'ALT-004',type:'Aniversario de Contrato',local:'OXXO',contractId:'CTR-8803',station:'Victorica',city:'Mazatlán',scheduledDate:'2026-09-12',recipients:['Coordinación Comercial'],recipientEmails:['comercial@redpetroil.com'],priority:'low',title:'Aniversario de contrato: OXXO · Victorica',description:'Revisar las obligaciones y actualizaciones aplicables por aniversario.'},
    {id:'ALT-005',type:'Vencimiento de Contrato',local:'Kiosko',contractId:'CTR-8804',station:'Munich Estadio',city:'Mazatlán',scheduledDate:'2026-09-18',recipients:['Alyn Ximena Reyes Navarrete','Área Legal'],recipientEmails:['alyn@redpetroil.com','legal@redpetroil.com'],priority:'high',title:'Vencimiento de contrato: Kiosko · Munich Estadio',description:'Iniciar negociación de renovación y revisar el expediente contractual.'}
  ];
  let stored=[];try{stored=JSON.parse(localStorage.getItem(key)||'[]');}catch{}const alerts=stored.length?stored:seed;if(!stored.length)localStorage.setItem(key,JSON.stringify(seed));
  const body=document.getElementById('scheduled-body'),search=document.getElementById('scheduled-search'),sort=document.getElementById('scheduled-sort'),count=document.getElementById('scheduled-count'),empty=document.getElementById('scheduled-empty'),dialog=document.getElementById('email-preview-dialog'),preview=document.getElementById('email-preview-content');
  const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),normalize=value=>String(value).toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,''),date=value=>new Date(`${value}T00:00:00`),days=value=>Math.ceil((date(value)-today)/86400000),priorityRank={high:3,medium:2,low:1},priorityLabel={high:'Alta',medium:'Media',low:'Baja'};
  const email=alert=>alert.emailHtml||`<div class="email-meta"><strong>De:</strong> Asset Management RedPetroil &lt;no-reply@redpetroil.com&gt;<br><strong>Para:</strong> ${escape((alert.recipientEmails||[]).join('; '))}<br><strong>Asunto:</strong> [${priorityLabel[alert.priority].toUpperCase()}] ${escape(alert.title)}</div><div class="email-body"><p>Estimado equipo,</p><p>Se genera una alerta de <strong>${escape(alert.type)}</strong> para <strong>${escape(alert.local)}</strong>, en la estación <strong>${escape(alert.station)}</strong>.</p><div class="email-alert priority-${alert.priority}">Envío programado para el ${date(alert.scheduledDate).toLocaleDateString('es-MX',{dateStyle:'long'})}.</div><p><em>Notas de gestión:</em> ${escape(alert.description)}</p></div>`;
  const render=()=>{const term=normalize(search.value),items=alerts.filter(alert=>!term||normalize(`${alert.type} ${alert.local} ${alert.station} ${(alert.recipients||[]).join(' ')}`).includes(term)).sort((a,b)=>sort.value==='priority'?(priorityRank[b.priority]-priorityRank[a.priority])||(date(a.scheduledDate)-date(b.scheduledDate)):date(a.scheduledDate)-date(b.scheduledDate));count.textContent=`${items.length} alertas`;empty.hidden=items.length>0;body.innerHTML=items.map(alert=>{const remaining=days(alert.scheduledDate);return `<tr><td><strong>${escape(alert.type)}</strong><small>${escape(alert.contractId)}</small></td><td><strong>${escape(alert.local)}</strong><small>${escape(alert.station)} · ${escape(alert.city)}</small></td><td><time>${date(alert.scheduledDate).toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'})}</time></td><td><span class="scheduled-days ${remaining<=3?'urgent':''}">${remaining<0?`Enviada hace ${Math.abs(remaining)} días`:remaining===0?'Se envía hoy':`${remaining} días`}</span></td><td><strong>${escape((alert.recipients||[])[0]||'Sin asignar')}</strong>${(alert.recipients||[]).length>1?`<small>+${alert.recipients.length-1} destinatario</small>`:''}</td><td><span class="scheduled-priority priority-${alert.priority}"><i></i>${priorityLabel[alert.priority]}</span></td><td><button type="button" class="preview-email" data-alert-id="${escape(alert.id)}"><span class="material-symbols-outlined">mail</span>Ver correo</button></td></tr>`}).join('');};
  body.addEventListener('click',event=>{const button=event.target.closest('[data-alert-id]');if(!button)return;const alert=alerts.find(item=>item.id===button.dataset.alertId);document.getElementById('email-preview-title').textContent=`${alert.type} · ${alert.local}`;preview.innerHTML=email(alert);dialog.showModal();});dialog.querySelectorAll('[data-close-preview]').forEach(button=>button.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});search.addEventListener('input',render);sort.addEventListener('change',render);render();
  if(new URLSearchParams(location.search).get('created')){const toast=document.getElementById('scheduled-toast');toast.textContent='Alerta guardada y programada correctamente.';toast.classList.add('visible');setTimeout(()=>toast.classList.remove('visible'),2600);}
});
